# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MLPerf inference submission checker

on:
  pull_request:
    branches: [ "main", "mlperf-inference-results-scc24" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CM_INDEX: "on"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install cm4mlops
    - name: Run MLPerf Inference Submission Checker
      run: |
        cm run script --tags=run,mlperf,inference,submission,checker,_short-run --adr.submission-checker-src.tags=_repo.https://github.com/gateoverflow/inference --version=r4.1  --quiet --extra_args=" --skip-extra-files-in-root-check" --submission_dir=./
